use_frameworks!

platform :ios, '10.0'

target 'YDFileManager_Example' do
  pod 'YDFileManager', :path => '../'

  target 'YDFileManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
